export {
  DspyAdapter,
  InstructionProposalSignature,
  TOOL_MODULE_PREFIX,
  ToolProposer,
  type DSPyAdapterConfig,
  type DSPyEvaluationHook,
  type DSPyExample,
  type DSPyFailedPrediction,
  type DSPyFeedbackFn,
  type DSPyPrediction,
  type DSPyPredictor,
  type DSPyProgram,
  type DSPyScoreWithFeedback,
  type DSPySignature,
  type DSPyTool,
  type DSPyTraceData,
  type DSPyTraceEntry,
} from './dspy_adapter.js';
